### ISSUE TITLE
Show poll results as bars

### ISSUE THREAD

**Issue by hdjirdeh** [hdjirdeh/angular2-hn#10]
So thanks to @mateuszwitkowski, we have poll support :)

Now the poll results show simply just like in Hacker News. I think it'll be pretty cool to show a nice poll results section wth bars (or chart) instead. I'm thinking separate bars with the largest result shown at 100% and the others as percentages based on their values (something just like this: https://app.hackerwebapp.com/#/item/6527104). We'll also want to make sure it fits for all screen sizes nicely.

I'm open to other ideas too! It doesn't have to be this exactly so let me know if you have any thoughts.

**Comment by bbrks** [comment]
I would advise making the total number of votes across all options be 100%. Example mockup:

![screenshot from 2016-12-30 12-19-49](https://cloud.githubusercontent.com/assets/1525809/21565004/5d8e8db8-ce8a-11e6-908b-39b2fda53a48.png)
![screenshot from 2016-12-30 12-20-23](https://cloud.githubusercontent.com/assets/1525809/21565003/5d8dc8ec-ce8a-11e6-8f4d-f0b4721dfc8f.png)

**Comment by hdjirdeh** [comment]
That looks perfect actually, agreed!

**Comment by bbrks** [comment]
I'll put together a PR tomorrow for this.

**Comment by hdjirdeh** [comment]
Thank so much mate, I appreciate it!
