### ISSUE TITLE
Webpack v2.1.0-beta.23 Issues

### ISSUE THREAD

**Issue by tahaipek** [hdjirdeh/angular2-hn#13]
I'm having the same issue. => [https://github.com/angular/angular-cli/issues/2234#issue-177927896](https://github.com/angular/angular-cli/issues/2234#issue-177927896)
Fix the webpack version in your app to v2.1.0-beta.22 for now.

I've added  "webpack": "2.1.0-beta.22" to devDependencies.

or

npm install webpack@2.1.0-beta.22 --save-dev

**Comment by hdjirdeh** [comment]
Thanks for this. Instead of doing that, I just updated to `1.0.0-beta.15` which fixes this issue 👍
