### ISSUE TITLE
Native packing

### ISSUE THREAD

**Issue by byukihara** [hdjirdeh/angular2-hn#17]
Very nice, @hdjirdeh 
Thanks for sharing.
In the screencast I see you are running it fullscreen natively.
Did you use phonegap? Is it builtin in your project?

**Comment by hdjirdeh** [comment]
Thank you @byukihara!

Are you referring to the README? Oh no I just rendered the webpage as mobile by setting Device Mode in the Chrome DevTools. I then recorded that portion of the screen as a .gif :)

**Comment by hdjirdeh** [comment]
Closing this now :)
