### ISSUE TITLE
Loading indicator shown even when calls to API result in an error

### ISSUE THREAD

**Issue by zachberger** [hdjirdeh/angular2-hn#21]
Currently when the API errors out the loading indicator continues to be shown. It would be nice if the user got a friendly error message when the API is down.

<img width="1920" alt="screen shot 2016-12-27 at 11 33 00 pm" src="https://cloud.githubusercontent.com/assets/1634878/21516421/f3265bbc-cc8c-11e6-9d8b-a66994ef9e26.png">

**Comment by hdjirdeh** [comment]
Good call, it doesn't make sense to keep showing the loading indicators instead of a simple error message.

**Comment by bfan1256** [comment]
Just a question, what code are you checking on whether or not there is data from the cache and whether or not you are receiving data from an api?

**Comment by housseindjirdeh** [comment]
@bfan1256 not at all! Please don't ever hesitate to ask questions. I'm glad you found my tutorial useful :)

So I specify a local [errorMessage](https://github.com/housseindjirdeh/angular2-hn/blob/master/src/app/item-details/item-details.component.ts#L20) string in each of my main components. When I subscribe to the Observable responsible for returning data, I specify on the [onError](https://github.com/housseindjirdeh/angular2-hn/blob/master/src/app/item-details/item-details.component.ts#L37) method to populate the `errorMessage` with a string.

Now in my template for the component, I use `ngIf` to [show the loading indicator](https://github.com/housseindjirdeh/angular2-hn/blob/master/src/app/item-details/item-details.component.html#L3) when there is no item and the error message field is blank. This scenario only passes if the request is still fetching. Similarly, I [show the actual content](https://github.com/housseindjirdeh/angular2-hn/blob/master/src/app/item-details/item-details.component.html#L5) only if the `item` object is populated.
