### ISSUE TITLE
Poll options should be displayed in the order defined in the poll story

### ISSUE THREAD

**Issue by zachberger** [hdjirdeh/angular2-hn#22]
Currently poll options are shown in the order the AJAX calls are returned. It would make sense to preserve the ordering that the story defines the options.

e.g. with arbitrary order, the story defined the values in ascending $ value
<img width="189" alt="screen shot 2016-12-27 at 11 36 45 pm" src="https://cloud.githubusercontent.com/assets/1634878/21516479/88821b56-cc8d-11e6-82cb-a9d453d9fb11.png">

**Comment by hdjirdeh** [comment]
Thanks again mate :) 

Surprised I didn't notice this!
