### ISSUE TITLE
Hovering the filter menu makes the other items move

### ISSUE THREAD

**Issue by thepiwo** [hdjirdeh/angular2-hn#24]
When hovering items from the `new | show | ask | jobs` menu the items after the hovered one move a slight bit due to the hovered item having more width by being bold.

**Comment by thepiwo** [comment]
I just recognized this was already mentioned in the hn comments: https://news.ycombinator.com/item?id=13268892

**Comment by hdjirdeh** [comment]
Yep, somebody mentioned it so was meaning to log an issue for it. Thanks a lot for filing it, appreciate it!
