### ISSUE TITLE
Too awesome...

### ISSUE THREAD

**Issue by archae0pteryx** [hdjirdeh/angular2-hn#27]
I have an issue. This is too awesome. I've been groping at a similar service for some weeks now and your code has taught me so much. Too much. Tone down the awesomeness will ya? Seriously though. Thanks!

**Comment by hdjirdeh** [comment]
😁 Thanks so much mate, this really means a lot. I appreciate it!

Not sure if you've seen it already but I wrote a [post](http://houssein.me/angular2-hacker-news) detailing how I built it. This was a few months ago so it isn't exactly what's on the master branch (like the service worker config for example) but I hope it helps.

Any questions on how/why I built anything on the app, don't hesitate to ask :)

**Comment by archae0pteryx** [comment]
I just may!
