### ISSUE TITLE
Open link on browser / share

### ISSUE THREAD

**Issue by SeriousM** [hdjirdeh/angular2-hn#31]
I'm using the reader as app and so it opens the links inside the app. 
Is there a way to open the link in another browser? 
Can we get a share functionality to eg. send the current page per mail or add it to pocket (another reader app)? 
Thank you very much!

**Comment by hdjirdeh** [comment]
Thanks for this. I've been toying with having links open in a new tab but decided not to as I feel it isn't the best mobile experience, especially when you have the app installed on your home screen. One thing I was considering was to give the user the ability to toggle in a small settings section in our application whether they want to open links in a new tab or not and I think this might be the best approach.

`<a href="..." [attr.target]="value ? '_blank' : undefined">`

For the share functionality, I'm assuming you're referring to the story link and not the comments page correct? Hmm we can explore that option (do we only allow sharing by mail or social media + pocket + others?) but definitely not a high priority.

**Comment by SeriousM** [comment]
Well, I would love to have the option to share the article url, comments
page or the current url (sometimes I go deeper in the article and want to
save it for later).

Sharing for pocket or mail is a vital function and I can't work without it.

**Comment by hdjirdeh** [comment]
Added a settings tab where you can now toggle whether you want story links to be opened in a separate tab 👍 

<img src="https://cloud.githubusercontent.com/assets/12476932/21575130/c2e712a2-ced0-11e6-9e68-a55d61800401.png" width="300" />

And thanks for the input, sharing wasn't something I was considering but if a number of folks find it useful then we'll have to explore that option. I'm going to close this ticket and open a separate one for that.

Let me know if opening links in a new tab works for you just fine!

**Comment by SeriousM** [comment]
Looks good!
In chrome I can share as I like to too! :+1:
Thanks
