### ISSUE TITLE
Non-URL stories show incorrect markup on mobile for title

### ISSUE THREAD

**Issue by hdjirdeh** [hdjirdeh/angular2-hn#34]
On mobile, story links that don't have a URL (for example, Ask HN stories) show the HTML markup instead of just the title text.

![Imgur](http://i.imgur.com/KQ30OMM.jpg)

‭

**Comment by bbrks** [comment]
I think I fixed this in #33 ([commit 458525ac76b9e3efcd4b4f65739f17b42b108049](https://github.com/hdjirdeh/angular2-hn/commit/458525ac76b9e3efcd4b4f65739f17b42b108049))

**Comment by hdjirdeh** [comment]
Oh you did! Awesome thanks so much, I just realized you fixed the typo on that file.
