### ISSUE TITLE
Service worker functionality in README

### ISSUE THREAD

**Issue by jamzi** [hdjirdeh/angular2-hn#37]
Hey. I love this hn client, great work.

Is there a typo in the docs for the service worker (PWA) part and in the package.json.

It says:
npm run sw to generate the service worker file
npm run static-serve to load the application along with the service worker asset using lite-server

I had to:
npm run precache instead of npm run sw
install lite-server from npm
change static-serve script to use lite-server not live-server
npm run static-serve

Should we add more detailed steps to docs and/or change package.json script too?

**Comment by hdjirdeh** [comment]
I'm glad you loved this app :)

And I'm so sorry, I had changed the script to `precache` and forgot to update the docs to reflect this. Also I'm actually using `live-server` not `lite-server` (although I think both should work 🤔 ) so it was a mistake to reference `lite-server` in the docs.

My apologies, I'll correct this in the next few minutes.

**Comment by hdjirdeh** [comment]
Done, please don't hesitate to ask if you run into any more issues!
