### ISSUE TITLE
Progressive Web Capabilities

### ISSUE THREAD

**Issue by hdjirdeh** [hdjirdeh/angular2-hn#5]
So the next major step for this app would be to make it a full blown progressive web app, and there's a CLI build just for that - [Angular Mobile Toolkit](https://github.com/angular/mobile-toolkit).

So here are some of the things that we can do to make this a progressive web application.
- App Shell functionality
- Work offline with the help of Service Workers
- Manifest file so these apps can be installed from browsers

Now the mobile toolkit comes with these features built in to it's configuration but it's still in an alpha stage. Nonetheless I would still prefer to get this done using --mobile, otherwise we can look into using [sw-precache](https://github.com/GoogleChrome/sw-precache) and [sw-toolbox](https://github.com/GoogleChrome/sw-toolbox) as well.

P.S. [Here's an earlier build of the application](https://github.com/hdjirdeh/angular2-hn-mobiletoolkit) using the mobile toolkit so feel free to take a look and see how I did things there. The App Shell and manifest files seemed to have worked but it did not work offline.

**Comment by robwormald** [comment]
cc @alxhub here, this would be a good test case for your newly revamped plugin.

**Comment by hdjirdeh** [comment]
Integrated sw-precache to cache App Shell + runtimeCaching of API and added a manifest file.
